# Generated by Django 5.0.6 on 2024-05-24 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_group_groupmessage_membership_group_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members', through='messaging.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
